class Solution:
    """
    You are given two strings s and t.

    String t is generated by random shuffling string s 
    and then add one more letter at a random position.

    Return the letter that was added to t.
    """
    def findTheDifference(self, s: str, t: str) -> str:
        result = 0
        for i in s+t:
            result ^= ord(i)

        return chr(result)

test = Solution()
print(test.findTheDifference("abcd", "abcde")) # e

                

